name: Quality tools

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node with version 16
              uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"
            - name: Install dependencies
              run: npm ci
            - name: Run Lint
              run: npm run lint

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node with version 16
              uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"
            - name: Install dependencies
              run: npm ci
            - name: Prepare test
              run: npm run pretest
            - name: Run tests
              uses: DevExpress/testcafe-action@latest
              with:
                  version: "1.18.6"
                  args: "all tests/e2e.ts --app 'npx sirv tests --port 5000'"
                  skip-install: true
